const {test}=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {downloadRequest,createDownloads}=require('../downloads.cjs');
const id='00000000-0000-4000-8000-000000000001';
const url=`https://fmyenjfzdwizpgretpkk.supabase.co/storage/v1/object/sign/chat-files/${id}/${id}/${id}.pdf?token=signed&download=recibo.pdf`;
function setup(){const session=new EventEmitter(),calls=[],contents={downloadURL:url=>calls.push(url)},window={isDestroyed:()=>false,setProgressBar:n=>calls.push(n)},timers={setTimeout:()=>1,clearTimeout(){}};const downloads=createDownloads({contents,session,getWindow:()=>window,downloadsPath:'/downloads',timers});return {session,calls,contents,downloads};}
function item(){const object=new EventEmitter();object.getURLChain=()=>[url];object.getTotalBytes=()=>100;object.getReceivedBytes=()=>50;object.getSavePath=()=>'/downloads/recibo.pdf';object.setSaveDialogOptions=options=>object.options=options;object.cancel=()=>object.emit('done',{},'cancelled');return object;}
test('only signed Conecta chat attachment URLs are accepted',()=>{assert(downloadRequest({url,name:'recibo.pdf'}));for(const bad of [url.replace('https:','http:'),url.replace('fmyenjfzdwizpgretpkk.supabase.co','evil.test'),url.replace('chat-files','profile-photos'),url.replace('token=signed','other=x'),url.replace('.pdf?','.exe?'),'file:///C:/file.pdf'])assert.equal(downloadRequest({url:bad,name:'x.pdf'}),null);});
test('suggested filename removes paths, invalid characters and reserved Windows names',()=>{assert.equal(downloadRequest({url,name:'../CON.pdf'}).name,'_CON.pdf');assert.equal(downloadRequest({url,name:'C:\\temp\\recibo.pdf'}).name,'recibo.pdf');assert.equal(downloadRequest({url,name:'malware.exe'}).name,'malware.exe.pdf');});
test('native download asks where to save and resolves after actual completion',async()=>{const s=setup(),pending=s.downloads.download({url,name:'recibo.pdf'}),i=item();s.session.emit('will-download',{preventDefault(){throw Error('unexpected cancellation');}},i,s.contents);assert.equal(i.options.defaultPath,'/downloads/recibo.pdf');assert.equal(i.options.title,'Salvar anexo do Conecta');i.emit('updated',{},'progressing');assert.equal(s.calls.at(-1),0.5);i.emit('done',{},'completed');assert.deepEqual(await pending,{ok:true,name:'recibo.pdf'});assert.equal(s.calls.at(-1),-1);});
test('cancel and network failure report different outcomes without executing files',async()=>{for(const state of ['cancelled','interrupted']){const s=setup(),pending=s.downloads.download({url,name:'recibo.pdf'}),i=item();s.session.emit('will-download',{preventDefault(){}},i,s.contents);i.emit('done',{},state);const result=await pending;assert.equal(result.ok,false);assert.equal(!!result.cancelled,state==='cancelled');if(state==='interrupted')assert(result.error);}});
test('unrequested downloads and redirects to other origins are blocked',async()=>{const s=setup();let blocked=0;s.session.emit('will-download',{preventDefault:()=>blocked++},item(),s.contents);assert.equal(blocked,1);const pending=s.downloads.download({url,name:'recibo.pdf'}),i=item();i.getURLChain=()=>[url,'https://evil.test/file.pdf'];s.session.emit('will-download',{preventDefault:()=>blocked++},i,s.contents);assert.equal(blocked,2);assert.equal((await pending).ok,false);});
test('a second click cannot start another download while one is active',async()=>{const s=setup(),pending=s.downloads.download({url,name:'recibo.pdf'});assert.equal((await s.downloads.download({url,name:'recibo.pdf'})).ok,false);assert.equal(s.calls.length,1);const i=item();s.session.emit('will-download',{preventDefault(){}},i,s.contents);i.emit('done',{},'cancelled');await pending;});
